---
version: "3"
services:
  backend:
    image: ghcr.io/suneelchenna/bc26-backend
    container_name: backend
    restart: always
    network_mode: "host"

  frontend:
    image: ghcr.io/suneelchenna/bc26-frontend
    container_name: frontend
    ports:
      - 3000:80
    restart: always
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
