version: "3"
services:

  backend:
    image: "ghcr.io/suneelchenna/bc26-backend"
    container_name: "backend"
    ports:
      - "8080:8080"
    restart: always  

  frontend:
    image: "ghcr.io/suneelchenna/bc26-frontend"
    container_name: "frontend"
    ports:
      - "3000:80"
    restart: always  
    depends_on:
      - backend

