---
name: deploy on aws ec2 backend
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/frontend.yml' 
env:
  REGISTRY: ghcr.io
jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package -DskipTests 
      - name: login gihub package
        run: docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_TOKEN }}
      - name: create build image
        run: docker build  -t ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/bc61-backend:${{ github.sha }} .
      - name: pushing image to github package
        run: docker push ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/bc61-backend:${{ github.sha }}

      - name: ssh connect to ec2 server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/ssh_private_key
          chmod 400 ~/ssh_private_key
          ssh -i ~/ssh_private_key -o StrictHostKeyChecking=no ubuntu@$REMOTE_HOST '

            docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_TOKEN }}
            docker stop backend 2>/dev/null;
            docker run -d -p 8080:8080 --name backend ghcr.io/suneelchenna/bc26-backend:${{ github.sha }} 

          
          

    

